/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef ALIGATOR_CONFIG_HH
# define ALIGATOR_CONFIG_HH

// Package version (header).
# define ALIGATOR_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define ALIGATOR_VERSION "0.15.0"
# define ALIGATOR_MAJOR_VERSION 0
# define ALIGATOR_MINOR_VERSION 15
# define ALIGATOR_PATCH_VERSION 0

#define ALIGATOR_VERSION_AT_LEAST(major, minor, patch) (ALIGATOR_MAJOR_VERSION>major || (ALIGATOR_MAJOR_VERSION>=major && \
                                                             (ALIGATOR_MINOR_VERSION>minor || (ALIGATOR_MINOR_VERSION>=minor && \
                                                                                                     ALIGATOR_PATCH_VERSION>=patch))))

#define ALIGATOR_VERSION_AT_MOST(major, minor, patch) (ALIGATOR_MAJOR_VERSION<major || (ALIGATOR_MAJOR_VERSION<=major && \
                                                            (ALIGATOR_MINOR_VERSION<minor || (ALIGATOR_MINOR_VERSION<=minor && \
                                                                                                     ALIGATOR_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
//
// Explicit template instantiation on Windows need to add
// dllexport on the definition and dllimport on the declaration.
// The XXX_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI macro
// should be set on the declaration while
// the XXX_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI macro
// should be set on the definition.
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define ALIGATOR_DLLIMPORT __declspec(dllimport)
#  define ALIGATOR_DLLEXPORT __declspec(dllexport)
#  define ALIGATOR_DLLLOCAL
#  define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __declspec(dllimport)
#  define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#  define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT __declspec(dllimport)
#  define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT __declspec(dllexport)
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define ALIGATOR_DLLIMPORT __attribute__ ((visibility("default")))
#   define ALIGATOR_DLLEXPORT __attribute__ ((visibility("default")))
#   define ALIGATOR_DLLLOCAL  __attribute__ ((visibility("hidden")))
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __attribute__ ((visibility("default")))
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT __attribute__ ((visibility("default")))
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define ALIGATOR_DLLIMPORT
#   define ALIGATOR_DLLEXPORT
#   define ALIGATOR_DLLLOCAL
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef ALIGATOR_STATIC
// If one is using the library statically, get rid of
// extra information and use standard explicit template
// instantiation keyword.
#  define ALIGATOR_DLLAPI
#  define ALIGATOR_LOCAL
#  define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION extern template
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export and
// define the right explicit template instantiation keyword.
#  ifdef aligator_EXPORTS
#   define ALIGATOR_DLLAPI ALIGATOR_DLLEXPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
#   define ALIGATOR_DLLAPI ALIGATOR_DLLIMPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI ALIGATOR_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI ALIGATOR_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#  endif // ALIGATOR_EXPORTS
#  define ALIGATOR_LOCAL ALIGATOR_DLLLOCAL
# endif // ALIGATOR_STATIC
#endif //! ALIGATOR_CONFIG_HH
