/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see
 * https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/tracy.hh.cmake for
 * details.
 */

#ifndef ALIGATOR_TRACY_HPP
#define ALIGATOR_TRACY_HPP



#ifdef ALIGATOR_TRACY_ENABLE
#if defined(__clang__) || defined(__GNUC__)
#define TracyFunction __PRETTY_FUNCTION__
#elif defined(_MSC_VER)
#define TracyFunction __FUNCSIG__
#endif
#include <tracy/Tracy.hpp>
#define ALIGATOR_TRACY_ZONE_SCOPED_N(name) ZoneScopedN(name)
#define ALIGATOR_TRACY_ZONE_SCOPED ZoneScoped
#define ALIGATOR_TRACY_ZONE_NAMED_N(varname, name, active) ZoneNamedN(varname, name, active)
#define ALIGATOR_TRACY_ZONE_NAMED(varname, active) ZoneNamed(varname, active)
#define ALIGATOR_TRACY_SET_THREAD_NAME(name) tracy::SetThreadName(name)
#else
#define ALIGATOR_TRACY_ZONE_SCOPED_N(x)
#define ALIGATOR_TRACY_ZONE_SCOPED
#define ALIGATOR_TRACY_ZONE_NAMED_N(x, y, z)
#define ALIGATOR_TRACY_ZONE_NAMED(x, y)
#define ALIGATOR_TRACY_SET_THREAD_NAME(x)
#endif

#endif  // ALIGATOR_TRACY_HPP
